services:
  api:
    image: <grpc-service-name>
    ports:
      - "7172:80"
      - "7443:443"
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    volumes:
      - ./movies-db.json:/app/movies-db.json
  cache:
    image: "redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
